[DO NOT MERGE] Lifecycle v2 enhancement (app upgrade)
adobe/aepsdk-core-ios pull request #1020
Opened 2024-05-02 20:04 UTC by yangyansong-adbe

Port changes from the Android side: https://github.com/adobe/aepsdk-core-android/pull/650

2024-05-13 15:52 UTC, cdhoffmann requested changes
Looks good but have a couple of questions/comments:
1. Can we write a test to check that isUpgrade is behaving as expected?
2. Is there a reason we decided not to add this function as part of the SystemInfoService?

2024-05-13 21:33 UTC, yangyansong-adbe commented
> Looks good but have a couple of questions/comments:
> 
> 1. Can we write a test to check that isUpgrade is behaving as expected?
> 2. Is there a reason we decided not to add this function as part of the SystemInfoService?

1. This [functional test](https://github.com/adobe/aepsdk-core-ios/blob/main/AEPLifecycle/Tests/FunctionalTests/LifecycleV2FunctionalTests.swift#L165) covered the upgrade use case. Also, the changes are inside the private functions, it's hard to cover them in unit tests. 
2. It's a good idea to move it to `SystemInfoService` if other extensions need to call this function as well. Currently, this version string is only used in the Lifecycle extension, so I would recommend not moving it.

2024-05-14 16:41 UTC, cdhoffmann approved these changes

2024-05-14 21:54 UTC, praveek commented
Can you add the following tests 
1) In LifecycleV2Extension changing applicationVersionNumber also triggers an upgrade event
2) In LifecycleExtension changing applicationVersionNumber does not count as upgrade

2024-05-15 18:44 UTC, praveek approved these changes

2024-05-15 19:59 UTC, merged